<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('clips', function (Blueprint $table) {
            $table->foreignId('cover_template_id')->nullable()->after('template_version_id')
                ->constrained('cover_templates')->nullOnDelete();
            // The headline actually burned into cover_path below — seeded from
            // clip_candidates.hook_text but independently editable, since the
            // punchiest hook text and the punchiest COVER text don't always match.
            $table->string('cover_text')->nullable()->after('cover_template_id');
            // Generated by CoverGeneratorService; published to social platforms
            // that support a custom thumbnail/cover (see PublishClipJob).
            $table->string('cover_path')->nullable()->after('cover_text');
        });
    }

    public function down(): void
    {
        Schema::table('clips', function (Blueprint $table) {
            $table->dropConstrainedForeignId('cover_template_id');
            $table->dropColumn(['cover_text', 'cover_path']);
        });
    }
};
